---
- name: Apply CIS Hardening
  hosts: all
  become: true

  vars:
    benchmark_version: "v2.0.0"
    system_is_ec2: true
    run_audit: false
    skip_for_travis: true
    fix_mode: true
    cis_rule_4_5_2_4_enabled: false

  roles:
    - role: ../AMAZON2-CIS-devel
  tasks:
    - name: Skip rule 4.5.2.4
      ansible.builtin.meta: end_play
      tags: cis_4.5.2.4