---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8

- name: Apply CIS Role
  hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - ../AMAZON2-CIS-devel