---
- name: Apply CIS Hardening
  hosts: all
  become: true

  vars:
    benchmark_version: "v2.0.0"
    system_is_ec2: true
    run_audit: false
    skip_for_travis: true
    fix_mode: true

  tasks:
    - name: Force disable CIS rule 4.5.2.4
      ansible.builtin.set_fact:
        cis_rule_4_5_2_4_enabled: false

    - name: Apply CIS role
      ansible.builtin.include_role:
        name: ansible-lockdown.AMAZON2-CIS
