---

- name: Audit_only | Show Audit Summary
  when:
      - audit_only
  ansible.builtin.debug:
      msg: "{{ audit_results.split('\n') }}"

- name: Audit_only | Stop Playbook Audit Only selected
  when:
      - audit_only
  ansible.builtin.meta: end_play
