name: Build AMI with CIS Hardening

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    env:
      TEMPLATE: example/build.pkr.hcl
      VAR_FILE_1: example/variables.pkr.hcl
      AWS_REGION: ap-southeast-1

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
      
      - name: Check ansible-playbook path
        run: which ansible-playbook

      - name: Clone AMAZON2-CIS role
        run: |
          mkdir -p example/roles/ansible-lockdown
          git clone https://github.com/ansible-lockdown/AMAZON2-CIS.git example/roles/ansible-lockdown/AMAZON2-CIS

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.7.10"

      - name: Validate Packer template
        run: |
          packer init $TEMPLATE
          packer validate -var-file="$VAR_FILE_1" $TEMPLATE

      - name: Clone AMAZON2-CIS role
        run: |
          mkdir -p example/roles/ansible-lockdown
          git clone https://github.com/ansible-lockdown/AMAZON2-CIS.git example/roles/ansible-lockdown/AMAZON2-CIS

      - name: Build AMI
        run: |
          packer build -var-file="$VAR_FILE_1" $TEMPLATE
