name: build-ami

on:
  push:

env:
  SUBNET_ID: "subnet-02b1a49c9406154543"

jobs:
  build-ami:
    runs-on: ubuntu-latest
    name: Build AMI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Action
        id: test-action
        uses: "./"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"
          packer-directory: "./example"
          var-file: "./example/amzn2.pkrvars.hcl"

      - name: Clean Up AMIs
        env:
          AMI_ID: ${{ steps.test-action.outputs.ami_id }}
        run: |
          aws ec2 deregister-image \
          --image-id $AMI_ID \
          --region ap-southeast-1
