name: Build AMI

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      TEMPLATE: example/build.pkr.hcl
      VAR_FILE_1: example/amzn2.pkrvars.hcl

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.0.0
        with:
          version: "1.7.10"

      - name: Validate Packer template
        run: |
          packer init $TEMPLATE
          packer validate -var-file="$VAR_FILE_1" $TEMPLATE

      - name: Build AMI
        run: |
          packer build -var-file="$VAR_FILE_1" $TEMPLATE
